### ISSUE TITLE
installation failure on Alpine Linux

### ISSUE THREAD

**Issue by bastistician** [emf-creaf/medfate#7]
Installation of medfate 4.4.0 from CRAN fails from `List control = NULL` here
https://github.com/emf-creaf/medfate/blob/1867fd0a7ccaeb53d33a4b45320e11a4e85242a5/src/inner_sperry.cpp#L16
with
```
g++ -std=gnu++17 -I"/QA/R-87210/build/include" -DNDEBUG  -I'/QA/R-87210/lib/Rcpp/include' -I'/QA/R-87210/lib/meteoland/include' -I/usr/local/include    -fpic  -O2 -mtune=native -Wno-ignored-attributes -Wno-deprecated-declarations -D__MUSL__   -c inner_sperry.cpp -o inner_sperry.o
inner_sperry.cpp:16:72: error: conversion from 'std::nullptr_t' to 'Rcpp::List' {aka 'Rcpp::Vector<19>'} is ambiguous
   16 |                        double sapFluidityDay = 1.0, List control = NULL) {
      |                                                                        ^
```

It should be possible to reproduce this error also for the development version via the [rhub/r-minimal Docker image](https://hub.docker.com/r/rhub/r-minimal):
```sh
docker run --rm -it rhub/r-minimal installr -d -t "linux-headers gfortran" emf-creaf/medfate
```
(this will take a while because 82 packages need to be downloaded and installed from source)

**Comment by miquelcaceres** [comment]
Thanks for reporting this installation issue. I tested installation with current commit in main branch, using the docker image, and seems to be solved.

**Comment by bastistician** [comment]
I can confirm that the current development version can be installed successfully on Alpine Linux. Any chance this could be released on CRAN? Thanks!

**Comment by miquelcaceres** [comment]
I will be released on CRAN in a few months. Is that ok or you would need it there sooner?

**Comment by bastistician** [comment]
The sooner the better. :)

**Comment by miquelcaceres** [comment]
medfate v.4.8.0 submitted to CRAN
